runtime: php55
api_version: 1

handlers:
- url: /(.+\.(ico|jpg|png|gif))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif))$
  application_readable: true

- url: /(.+\.(php|htm|html|css|js))$
  static_files: \4
  upload: (.+\.(php|htm|html|css|js))$
  application_readable: true

- url: /(.+\.php)$
  script: \5


- url: /.*
  script: index.php
